# welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr=np.array([[3,4,5,6]],np.int8)

In [3]:
myarr[0,1]

np.int8(4)

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int8')

In [6]:
myarr[0,1]=45

In [7]:
myarr

array([[ 3, 45,  5,  6]], dtype=int8)

# Array creation: conversion from other python structure

In [8]:
listarray = np.array([[1,2,3],[5,8,7],[8,9,7]])

In [9]:
listarray

array([[1, 2, 3],
       [5, 8, 7],
       [8, 9, 7]])

In [11]:
listarray.dtype

dtype('int64')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [15]:
zeros= np.zeros((2,5))

In [18]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
rng= np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
lspace= np.linspace(1,5,5)

In [26]:
lspace

array([1., 2., 3., 4., 5.])

In [27]:
emp= np.empty((4,6))

In [28]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23047842e-307, 2.22526399e-307, 6.23053614e-307],
       [1.29060871e-306, 6.23055651e-307, 1.06811422e-306,
        3.56043054e-307, 1.37961641e-306, 1.05695167e-307],
       [1.78020169e-306, 7.56601165e-307, 1.02359984e-306,
        1.33510679e-306, 2.22522597e-306, 8.01097889e-307],
       [1.60218491e-306, 1.78022342e-306, 1.78019082e-306,
        1.11260144e-306, 8.34448533e-308, 3.91792476e-317]])

In [29]:
emp_like= np.empty_like(lspace)

In [30]:
emp_like

array([1., 2., 3., 4., 5.])

In [33]:
ide=np.identity(5)

In [34]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
ide.shape

(5, 5)

In [37]:
arr=np.arange(99)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr =arr.reshape(3,33)

In [41]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [43]:
arr =arr.ravel()

In [44]:
arr.shape

(99,)

In [46]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [47]:
ar=np.array(x)

In [48]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [49]:
ar.sum(axis=0)

array([12,  8,  9])

In [50]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [51]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [52]:
ar.flat

In [53]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [54]:
ar.ndim

2

In [55]:
ar.size

9

In [56]:
ar.nbytes

72

In [57]:
one=np.array([1,2,3,4,5])

In [58]:
one.argmax()

np.int64(4)

In [59]:
one.argmin()

np.int64(0)

In [60]:
one.argsort()

array([0, 1, 2, 3, 4])

In [61]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
ar.argmin()

np.int64(8)

In [66]:
ar.argmax()

np.int64(6)

In [68]:
ar.argmax(axis=0)

array([2, 1, 1])

In [69]:
ar.argmax(axis=1)

array([2, 2, 0])

In [70]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [71]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [72]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [76]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [79]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [77]:
ar2=np.array([[1,2,1],
             [4,0,6],
             [8,1,0]])

In [78]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [80]:
[324,34]+[34,546]

[324, 34, 34, 546]

In [81]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [85]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [86]:
ar.sum()

np.int64(29)

In [87]:
ar.min()

np.int64(0)

In [88]:
ar.max()

np.int64(7)

In [89]:
np.where(ar>=5)

(array([1, 1, 2]), array([1, 2, 0]))

In [90]:
np.count_nonzero(ar)

8

In [91]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [92]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [93]:
ar[1,2]=0

In [94]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [95]:
import sys

In [96]:
py_ar=[0,4,55,2]

In [97]:
np_ar=np.array(py_ar)

In [100]:
sys.getsizeof(1)*len(py_ar)

112

In [104]:
np_ar.itemsize*np_ar.size

32